export const IPC = {
  // Renderer -> Main (invoke)
  USERS_LIST: 'users:list',
  USERS_CREATE: 'users:create',
  USERS_SELECT: 'users:select',
  PIPELINE_RUN: 'pipeline:run',
  PIPELINE_RUN_COMPANY: 'pipeline:run-company',
  COMPANIES_LIST: 'companies:list',
  COMPANIES_ADD: 'companies:add',
  COMPANIES_REMOVE: 'companies:remove',
  COMPANIES_TOGGLE: 'companies:toggle',
  INDEX_RUN: 'index:run',
  INDEX_COMPANY: 'index:company',
  KANBAN_COLUMNS: 'kanban:columns',
  KANBAN_MOVE: 'kanban:move',
  RESULTS_LIST_RUNS: 'results:list-runs',
  RESULTS_GET_RUN: 'results:get-run',
  RESULTS_GET_JOBS: 'results:get-jobs',
  DOCS_LIST: 'docs:list',
  DOCS_READ: 'docs:read',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  OPEN_URL: 'open-url',
  // Main -> Renderer (push)
  PIPELINE_STAGE_UPDATE: 'pipeline:stage-update',
  PIPELINE_PROVIDER_UPDATE: 'pipeline:provider-update',
  PIPELINE_ENRICHMENT: 'pipeline:enrichment',
  PIPELINE_DONE: 'pipeline:done',
  PIPELINE_ERROR: 'pipeline:error',
  INDEX_NEW_JOBS: 'index:new-jobs',
} as const;
