export const IPC = {
  // Renderer -> Main (invoke)
  USERS_LIST: 'users:list',
  USERS_CREATE: 'users:create',
  USERS_SELECT: 'users:select',
  USERS_CURRENT: 'users:current',
  PIPELINE_RUN: 'pipeline:run',
  PIPELINE_RUN_COMPANY: 'pipeline:run-company',
  COMPANIES_LIST: 'companies:list',
  COMPANIES_ADD: 'companies:add',
  COMPANIES_REMOVE: 'companies:remove',
  COMPANIES_TOGGLE: 'companies:toggle',
  COMPANIES_SET_FILTERS: 'companies:set-filters',
  INDEX_RUN: 'index:run',
  INDEX_COMPANY: 'index:company',
  KANBAN_COLUMNS: 'kanban:columns',
  KANBAN_MOVE: 'kanban:move',
  KANBAN_STAGE_COUNTS: 'kanban:stage-counts',
  KANBAN_RECENT_ACTIVITY: 'kanban:recent-activity',
  RESULTS_LIST_RUNS: 'results:list-runs',
  RESULTS_GET_RUN: 'results:get-run',
  RESULTS_GET_JOBS: 'results:get-jobs',
  DOCS_LIST: 'docs:list',
  DOCS_READ: 'docs:read',
  DOCS_IMPORT: 'docs:import',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  OLLAMA_MODELS: 'ollama:models',
  PROFILE_GET: 'profile:get',
  PROFILE_PARSE: 'profile:parse',
  PROFILE_SAVE: 'profile:save',
  OPEN_URL: 'open-url',
  RESULTS_GET_ALL_JOBS: 'results:get-all-jobs',
  KANBAN_FEEDBACK_SUMMARY: 'kanban:feedback-summary',
  TRACES_LIST_RUNS: 'traces:list-runs',
  TRACES_GET_EVENTS: 'traces:get-events',
  TRACES_GET_LLM_CALLS: 'traces:get-llm-calls',
  TRACES_GET_LLM_CALL: 'traces:get-llm-call',
  // Main -> Renderer (push)
  PIPELINE_STAGE_UPDATE: 'pipeline:stage-update',
  PIPELINE_PROVIDER_UPDATE: 'pipeline:provider-update',
  PIPELINE_ENRICHMENT: 'pipeline:enrichment',
  PIPELINE_ITERATION: 'pipeline:iteration',
  PIPELINE_DONE: 'pipeline:done',
  PIPELINE_ERROR: 'pipeline:error',
  INDEX_NEW_JOBS: 'index:new-jobs',
  PIPELINE_JOB_PROGRESS: 'pipeline:job-progress',
} as const;
